version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production # Use production stage for production deployment
    container_name: skybook-api-prod
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://skybook_user:skybook_password@postgres:5432/skybook
      - PORT=3000
    depends_on:
      postgres:
        condition: service_healthy
    command: node dist/main

  postgres:
    image: postgres:15-alpine
    container_name: skybook-postgres-prod
    restart: always
    environment:
      POSTGRES_DB: skybook
      POSTGRES_USER: skybook_user
      POSTGRES_PASSWORD: skybook_password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U skybook_user -d skybook']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_prod:
